CREATE SCHEMA IF NOT EXISTS vehicle_schema;
CREATE SCHEMA IF NOT EXISTS history_schema; 
CREATE SCHEMA IF NOT EXISTS paperwork_schema;
CREATE SCHEMA IF NOT EXISTS transport_schema; 
CREATE SCHEMA IF NOT EXISTS auction_analyzer_schema; 

CREATE TABLE vehicle_schema.vehicles (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    vin VARCHAR(17) NOT NULL UNIQUE,
    model_year SMALLINT NOT NULL,
    keys_present BOOLEAN,
    odometer INTEGER,
    make VARCHAR(100) NOT NULL,
    model VARCHAR(100) NOT NULL,
    body_type VARCHAR(100) NOT NULL,
    trim VARCHAR(100),
    color VARCHAR(50),
    engine VARCHAR(100),
    transmission VARCHAR(50),
    drivetrain VARCHAR(20),
    created_at TIMESTAMPTZ NOT NULL,
    updated_at TIMESTAMPTZ NOT NULL,

    CONSTRAINT pk_vehicles PRIMARY KEY (id),
    CONSTRAINT uk_vehicles_vin UNIQUE (vin)
);

CREATE INDEX idx_vehicles_make_model
    ON vehicle_schema.vehicles (make, model);

CREATE TABLE history_schema.vehicle_history (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    vehicle_id BIGINT NOT NULL UNIQUE,
    previous_owners INTEGER,
    previous_accidents INTEGER,
    damage_code VARCHAR(50),
    classification VARCHAR(50) NOT NULL,
    airbag_status VARCHAR(30),
    created_at TIMESTAMPTZ NOT NULL,
    updated_at TIMESTAMPTZ NOT NULL,

    CONSTRAINT fk_history_listing
        FOREIGN KEY (vehicle_id)
        REFERENCES vehicle_schema.vehicles(id) ON DELETE CASCADE
);

CREATE TABLE paperwork_schema.paperwork_information (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    vehicle_id BIGINT NOT NULL UNIQUE, 
    title_status VARCHAR(30) NOT NULL, 
    title_state VARCHAR(2), 
    lien_status VARCHAR(30),
    bill_of_sale_present BOOLEAN, 
    auction_fees NUMERIC(12,2), 
    created_at TIMESTAMPTZ NOT NULL, 
    updated_at TIMESTAMPTZ NOT NULL,

    CONSTRAINT fk_paperwork_vehicle 
        FOREIGN KEY(vehicle_id) 
        REFERENCES vehicle_schema.vehicles(id) ON DELETE CASCADE
);

CREATE TABLE transport_schema.vehicle_transport_estimate (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    vehicle_id BIGINT NOT NULL UNIQUE, 
    pickup_location VARCHAR(255) NOT NULL, 
    distance_in_miles INTEGER NOT NULL,
    operability VARCHAR(255) NOT NULL, 
    trailer_type VARCHAR(255) NOT NULL, 
    vehicle_type VARCHAR(255) NOT NULL,
    additional_fees NUMERIC(12,2) NOT NULL, 
    estimated_cost NUMERIC(12,2) NOT NULL,
    created_at TIMESTAMPTZ NOT NULL, 
    updated_at TIMESTAMPTZ NOT NULL,

    CONSTRAINT fk_transport_vehicle 
        FOREIGN KEY(vehicle_id) 
        REFERENCES vehicle_schema.vehicles(id) ON DELETE CASCADE
);

CREATE TABLE auction_analyzer_schema.auction_pricing (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    vehicle_id BIGINT NOT NULL UNIQUE, 
    purchase_price NUMERIC(12,2) NOT NULL, 
    estimated_market_value NUMERIC(12,2) NOT NULL,
    estimated_repair_cost NUMERIC(12,2) NOT NULL, 
    transport_cost NUMERIC(12,2) NOT NULL, 
    auction_fees NUMERIC(12,2) NOT NULL,
    title_adjustment_cost NUMERIC(12,2) NOT NULL, 
    profit_goal NUMERIC(12,2) NOT NULL, 
    total_cost NUMERIC(12,2) NOT NULL,
    max_bid NUMERIC(12,2) NOT NULL, 
    expected_profit NUMERIC(12,2) NOT NULL, 
    is_good_purchase BOOLEAN NOT NULL,
    created_at TIMESTAMPTZ NOT NULL, 
    updated_at TIMESTAMPTZ NOT NULL,

    CONSTRAINT fk_analysis_vehicle 
        FOREIGN KEY(vehicle_id) 
        REFERENCES vehicle_schema.vehicles(id) ON DELETE CASCADE
);


