CREATE SCHEMA IF NOT EXISTS auction_listing_schema;

CREATE TABLE auction_listing_schema.auction_listings (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    source_record_id VARCHAR(100) NOT NULL,
    source_first_seen_at TIMESTAMPTZ,
    source_last_seen_at TIMESTAMPTZ,
    stock_number VARCHAR(50),
    item_id VARCHAR(50),
    salvage_id VARCHAR(50),
    external_auction_id VARCHAR(50),

    model_year SMALLINT NOT NULL,
    make VARCHAR(100) NOT NULL,
    model VARCHAR(100) NOT NULL,
    series VARCHAR(100),
    body_style VARCHAR(100),
    exterior_color VARCHAR(50),
    engine VARCHAR(255),
    cylinders SMALLINT,
    transmission VARCHAR(50),
    drivetrain VARCHAR(30),
    fuel_type VARCHAR(50),

    primary_damage VARCHAR(100),
    secondary_damage VARCHAR(100),
    loss_type VARCHAR(50),

    title_type VARCHAR(50),
    title_code VARCHAR(20),
    title_state VARCHAR(10),

    has_keys BOOLEAN,
    run_and_drive BOOLEAN,
    starts_description VARCHAR(50),

    mileage INTEGER,
    odometer_brand VARCHAR(30),
    odometer_unit VARCHAR(10),
    airbag_state VARCHAR(30),
    vehicle_grade SMALLINT,

    auction_datetime TIMESTAMPTZ,
    branch_number VARCHAR(20),
    branch_name VARCHAR(100),
    location_city VARCHAR(100),
    location_state VARCHAR(10),
    location_latitude DOUBLE PRECISION,
    location_longitude DOUBLE PRECISION,

    provider_type VARCHAR(30),
    country_of_origin VARCHAR(100),

    created_at TIMESTAMPTZ NOT NULL,
    updated_at TIMESTAMPTZ NOT NULL,

    CONSTRAINT uk_auction_listing_source_record
        UNIQUE (source_record_id)
);

CREATE INDEX idx_auction_listing_vehicle
    ON auction_listing_schema.auction_listings
    (make, model, model_year);

CREATE INDEX idx_auction_listing_auction_datetime
    ON auction_listing_schema.auction_listings
    (auction_datetime);