ALTER TABLE auction_listing_schema.auction_listings
    ADD COLUMN IF NOT EXISTS vin VARCHAR(17),
    ADD COLUMN IF NOT EXISTS current_bid NUMERIC(12, 2);

CREATE INDEX IF NOT EXISTS idx_auction_listing_provider
    ON auction_listing_schema.auction_listings(provider_type);

CREATE INDEX IF NOT EXISTS idx_auction_listing_vin
    ON auction_listing_schema.auction_listings(vin);

CREATE SCHEMA IF NOT EXISTS auction_analyzer_schema;

CREATE TABLE IF NOT EXISTS auction_analyzer_schema.listing_analysis (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    listing_id BIGINT NOT NULL UNIQUE,

    estimated_market_value NUMERIC(12, 2) NOT NULL,
    estimated_repair_cost NUMERIC(12, 2) NOT NULL,
    transport_cost NUMERIC(12, 2) NOT NULL,
    auction_fees NUMERIC(12, 2) NOT NULL,
    title_adjustment_cost NUMERIC(12, 2) NOT NULL,

    total_cost NUMERIC(12, 2) NOT NULL,
    expected_profit NUMERIC(12, 2) NOT NULL,
    roi_percent NUMERIC(10, 2) NOT NULL,
    max_bid NUMERIC(12, 2) NOT NULL,

    opportunity_score INTEGER NOT NULL,
    risk_level VARCHAR(20) NOT NULL,
    is_good_purchase BOOLEAN NOT NULL,

    created_at TIMESTAMPTZ NOT NULL,
    updated_at TIMESTAMPTZ NOT NULL,

    CONSTRAINT fk_listing_analysis_listing
        FOREIGN KEY (listing_id)
        REFERENCES auction_listing_schema.auction_listings(id)
        ON DELETE CASCADE
);

CREATE INDEX IF NOT EXISTS idx_listing_analysis_roi
    ON auction_analyzer_schema.listing_analysis(roi_percent DESC);

CREATE INDEX IF NOT EXISTS idx_listing_analysis_profit
    ON auction_analyzer_schema.listing_analysis(expected_profit DESC);

CREATE INDEX IF NOT EXISTS idx_listing_analysis_score
    ON auction_analyzer_schema.listing_analysis(opportunity_score DESC);