spring.datasource.url=jdbc:postgresql://localhost:5432/car_auction_test
spring.datasource.username=ivanibarra
spring.datasource.password={DB_PASSWORD;}

spring.jpa.hibernate.ddl-auto=validate
spring.flyway.enabled=true